Source/DelphiAST.Writer.pas
This will solve #45.
I tried using TStringStream also but that was slower than using TStringBuilder.
I think this could be done even faster but it needed less than 500ms for the 126K LOC monster FMX.DAE.Schema.pas which I found reasonably fast.
Oh, and I added a formatting option which is also much faster than using FormatXMLData.
=> implemented TSyntaxTreeWriter.ToXML in a faster way than using TXMLDocument

Source/DelphiAST.pas
Forward declarations of classes work well while forward declarations of interfaces didn't. With this change forwarding works wih interfaces too.
=> Forward declarations of interfaces are now recoginzed

Source/DelphiAST.pas, Source/SimpleParser/SimpleParser.pas, Test/Snippets/tryexcept.pas
Exceptionhandlers can now contain a node of ntVariable for `on E: Exception do` or a node of ntType for `on Exception do`.
The else branch in `except`block is now also represented in AST.
=> Fix #98: Exceptionhandlers are not fully supported 

Source/DelphiAST.pas
I require to know where a method, typedeclaration, interface section, implementation section and uses section end. So I use TCompoundSyntaxNode more often in my own fork. Maybe it's helpful to others to pull these changes
=> More usage of TCompoundSyntaxNode

README.md, Source/DelphiAST.Classes.pas, Source/DelphiAST.Consts.pas, Source/DelphiAST.Writer.pas, Source/DelphiAST.pas
A syntax node's Attributes[] dictionary (and related methods) now use an enum for the attribute name instead of a string.
This is unlikely to reduce string memory usage much, since the compiler merges identical compile-time strings, but is a plus for correctness (compiler catches spelling errors) and is neater.  It is also a good basis for upcoming code to merge all attribute values - coming soon :)
=> Attributes use enums instead of strings as keys

Source/SimpleParser/SimpleParser.Lexer.Types.pas, Source/SimpleParser/SimpleParser.Lexer.pas
The current implementation for including files can cause a buffer overflow when a file includes more than 2 MB. That error is fixed by this pull request.
=> Fixed buffer overflow on including more than 2 MB into a file

Source/DelphiAST.Classes.pas, Source/DelphiAST.pas
I had a look at the memory comsumption of DelphiAST.
An **empty** instance of **`TSyntaxNode`** (no child nodes, no attributes, empty file name) reserves **148 byte**. In huge files we can have more than 100k instances of that class. So the memory consumption matters.
I've seen **60 byte** are reserved for **`FChildNode: TObjectList<TSyntaxNode>`** and **52 byte** are used for **`FAttributes: TDictionary<TAttributeName, string>`**
I reimplemented these members as arrays and had a look at the performance. I tested with a slightly modified version of JEDI's `mscorlib_tlb.pas` (~1.5 MB). 
**The results:**
Test|Empty node size|Size of AST for `mscorlib_tlb`|Duration for building the AST
----|---------------|------------------------------|-----------------------------
ChildNodes as …
=> Performance improvement

Source/DelphiAST.Classes.pas
The FileName value was lost on cloning a `TSyntaxNode`.
=> Fix: TSyntaxNode.Clone didn't clone FileName property

Source/DelphiAST.pas
Exceptions of type `ESyntaxError` haven't been handled properly in `TPasSyntaxTreeBuilder`.
=> TPasSyntaxTreeBuilder handles ESyntaxError properly

Source/DelphiAST.pas
When the `FOnMessage` event doesn't throw an exception when a var section contains syntax errors then `TypeInfo` can be `nil`.
=> Added assignment check before cloning

Source/SimpleParser/SimpleParser.pas
I don't know why the parser handles `ptIdentifier` so different here. But when you parse a file that starts with statements like the following then you receive an empty tree. 
A file like this:
```pascal
MyObject.DoWhatever(5);
```
now results in a valid tree.
Was there any particular reason for handling `ptIdentifier` differently?
=> Files with statements only can be parsed

Demo/DelphiASTDemo.dpr, Demo/StringUsageLogging.pas, Demo/uMainForm.dfm, Demo/uMainForm.pas, Source/DelphiAST.pas, Source/SimpleParser/SimpleParser.Lexer.pas, Source/StringPool.pas
I added the possibility to activate string interning.
My goal was to be as unintrusive with this feature as possible so I added an event that you can attach to the TPasSyntaxTreeBuilder. If you pass nil it behaves as it currently does (possibly allocating hundreds and thousands of strings with identical content).
To keep this all inside the TPasSyntaxTreeBuilder and not in the underlying lexer I added a wrapper for the lexer to call the interning in the GetToken method.
In the demo you can see how speed and memory consumption changes with or without the interning.
Optionally for diagnostic purpose you can remove the comments from LogStringUsageToFile and let it output all duplicate strings in the memory manager (using FastMM4) - this may take a few seconds.
=> implemented string interning

Source/SimpleParser/SimpleParser.Lexer.pas
If $INCLUDE/$I is found while in the $IF(N)DEF/$IF part which is being skipped (undefined conditional etc), include is ignored.
This speeds up parsing (especially if include file has to be found in a long search path) and makes the parser more compatible with Delphi which ignores $INCLUDE statements inside skipped blocks.
Example:
{$IFDEF DELPHI}
{$I delphi.inc}
{$ELSE}
{$I notdelphi.inc}
{$ENDIF}
When parsing for Delphi (DELPHI is defined), delphi.inc is included and notdelphi.inc is skipped.
Without this fix both .inc files are included and parsed.
=> don't $I files when inside skipped $IFDEF/$IF

Source/SimpleParser/SimpleParser.Lexer.pas
Lexer can now handle $IF statements in form
{$IF CompilerVersion operator value}
and
{$IF RTLVersion operator value}
This covers most frequent use-cases of CompilerVersion and RTLVersion.
=> extended $IF support

Source/DelphiAST.pas, Source/SimpleParser/SimpleParser.Lexer.Types.pas, Source/SimpleParser/SimpleParser.Lexer.pas, Source/SimpleParser/SimpleParser.pas
With this PR scoped enums can be identified by the additional visibility attribute. This attribute is only present in the rare case of a scoped enum.
=> Added support for scoped enums. Fixes #184

Source/DelphiAST.Classes.pas, Source/DelphiAST.Consts.pas, Source/DelphiAST.pas
In the AST the descendant nodes after the "absolute" node and before the "identifier" node was deleted.
=> In the AST the descendant nodes after the "absolute" node and before the "identifier" node was deleted.

Source/SimpleParser/SimpleParser.Lexer.pas
I replaced the AddDefine('VERxxx') calls with a generalized version that uses the current value of COMPILERVERSION. That way the code automatically adapts to new Delphi versions.
I noticed that although the SimpleParser.inc was adjusted to 10.3 Rio, the InitDefinesDefinedByCompiler missed that part. With the above change these additions are no longer necessary.
=> generalized adding VER defines depending on COMPILERVERSION

Demo/Parser/uMainForm.pas, Source/DelphiAST.ProjectIndexer.pas, Source/SimpleParser/SimpleParser.Lexer.Types.pas, Source/SimpleParser/SimpleParser.Lexer.pas, Test/uMainForm.pas
In order to provide more information for `IIncludeHandler.GetIncludeFileContent()` implementation, I've made few changes.
This is needed in to be able to find .inc files in complex cases.
For example, you include `jcl.inc`. It's in your search path. So you can easily find it. Then `jcl.inc` has this line:
```
{$I jedi\jedi.inc} // Pull in the JCL/J-VCL shared directives
```
`jedi\jedi.inc` path is relative to `jcl.inc`. Thus order to find it, `IIncludeHandler` implementation needs to know full path to `jcl.inc`. That's why `ParentFileName` is passed to `GetIncludeFileContent()`.
=> Update IIncludeHandler interface

Source/DelphiAST.ProjectIndexer.pas
We had concurrency issues when running several instances of a small tool based on DelphiAST in parallel.
After running the tool with this fix for ten work days, I can say that the concurrency issues are gone. 
Perhaps this also resolves the concurrency issues that I have observed with FixInsight? ;)
=> Allow shared read access to parsed files

Source/DelphiAST.Consts.pas, Source/DelphiAST.pas, Source/SimpleParser/SimpleParser.Lexer.Types.pas, Source/SimpleParser/SimpleParser.Lexer.pas, Source/SimpleParser/SimpleParser.pas, Test/Snippets/alignedrecords.pas, Test/Snippets/nonalignedrecords.pas
I figured out the issue I had with resolving the alignment attribute. In the parser, I had to create 2 additional virtual methods: RecordAlignment and RecordAlignmentValue.
I've added 2 snippets, one with and without alignment.
=> Add support for alignment on records
